name: Bless the code

on: 
  push:
    branches:
      - main
      - v1.0.0
  pull_request:
    branches:
      - main
      - v1.0.0
env:
  MIX_ENV: test
  ES_VERSION: 4

jobs:
  ES-21:
    name: ES 21.10.9
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        elixir: ['1.12.3', '1.14.2']
        erlang: ['24.1', '25.2']

    services:
      es:
        image: eventstore/eventstore:21.10.9-buster-slim
        ports: ['1113:1113']
        env:
          EVENTSTORE_RUN_PROJECTIONS: "All"
          EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
          EVENTSTORE_CLUSTER_SIZE: 1
          EVENTSTORE_EXT_TCP_PORT: 1113
          EVENTSTORE_INSECURE: "true"
          EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        version-type: strict
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.erlang }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.erlang }}-
    - name: Install dependencies
      run: mix deps.get
    - name: Restore builds cache
      uses: actions/cache@v2
      with:
        path: _build/test
        key: ${{ runner.os }}-build_test-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-build_test-${{ matrix.elixir }}-${{ matrix.erlang }}-
    - name: Check warnings
      run: mix compile --warnings-as-errors --force
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run tests
      run: mix test --cover --exclude=authentication

  ES-22:
    name: ES 22.10.0
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        elixir: ['1.12.3', '1.14.2']
        erlang: ['24.1', '25.2']

    services:
      es:
        image: eventstore/eventstore:22.10.1-buster-slim
        ports: ['1113:1113']
        env:
          EVENTSTORE_RUN_PROJECTIONS: "All"
          EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
          EVENTSTORE_CLUSTER_SIZE: 1
          EVENTSTORE_EXT_TCP_PORT: 1113
          EVENTSTORE_INSECURE: "true"
          EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        version-type: strict
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.erlang }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.erlang }}-
    - name: Install dependencies
      run: mix deps.get
    - name: Restore builds cache
      uses: actions/cache@v2
      with:
        path: _build/test
        key: ${{ runner.os }}-build_test-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-build_test-${{ matrix.elixir }}-${{ matrix.erlang }}-
    - name: Check warnings
      run: mix compile --warnings-as-errors --force
    - name: Check formatting
      run: mix format --check-formatted
    - name: Run tests
      run: mix test --cover
